"""Export G1 kinematic + inertial constants to a generated CUDA header.

A single-world POC bakes the model in at compile time (no runtime MJCF parsing on
the GPU). Emits src/g1_model.h with everything a from-scratch articulated-body
engine needs, in MuJoCo's dof/qpos ordering so joint-space quantities (M,
qfrc_bias, qacc) can be compared directly.

Free-joint velocity convention (probed empirically, see gen_reference.py):
  qvel[0:3] = base linear velocity in WORLD frame
  qvel[3:6] = base angular velocity in BODY-LOCAL frame
"""
import os
import numpy as np
import mujoco

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = os.path.join(HERE, "models", "g1.xml")
OUT = os.path.join(HERE, "src", "g1_model.h")


def fmtf(v):
    """Format a float as a valid C float literal (always has '.' or exponent)."""
    s = f"{float(v):.9g}"
    if not any(c in s for c in ".eEnf"):  # int-looking -> add decimal
        s += ".0"
    return s + "f"


def carr(name, arr, ncol):
    """Format a flat float array as a C initializer, ncol values per row."""
    flat = np.asarray(arr, dtype=np.float64).ravel()
    vals = [fmtf(v) for v in flat]
    rows = [", ".join(vals[i:i + ncol]) for i in range(0, len(vals), ncol)]
    body = ",\n  ".join(rows)
    return f"__device__ __constant__ float {name}[{len(flat)}] = {{\n  {body}\n}};\n"


def iarr(name, arr):
    flat = np.asarray(arr, dtype=np.int64).ravel()
    vals = ", ".join(str(int(v)) for v in flat)
    return f"__device__ __constant__ int {name}[{len(flat)}] = {{ {vals} }};\n"


def main():
    m = mujoco.MjModel.from_xml_path(MODEL)
    nb, nv, nq, njnt = m.nbody, m.nv, m.nq, m.njnt

    lines = []
    lines.append("// GENERATED by scripts/export_model.py -- do not edit by hand.")
    lines.append("// Unitree G1 (models/g1.xml), MuJoCo dof/qpos ordering.")
    lines.append("#pragma once\n")
    lines.append(f"#define G1_NBODY {nb}")
    lines.append(f"#define G1_NQ {nq}")
    lines.append(f"#define G1_NV {nv}")
    lines.append(f"#define G1_NJNT {njnt}")
    lines.append(f"#define G1_DT {m.opt.timestep:.9g}f")
    g = m.opt.gravity
    lines.append(f"__device__ __constant__ float G1_GRAVITY[3] = {{ {fmtf(g[0])}, {fmtf(g[1])}, {fmtf(g[2])} }};\n")

    # --- body tree ---
    lines.append(iarr("body_parentid", m.body_parentid))
    lines.append(carr("body_pos", m.body_pos, 3))      # parent-frame translation
    lines.append(carr("body_quat", m.body_quat, 4))    # parent-frame rotation (wxyz)
    lines.append(carr("body_ipos", m.body_ipos, 3))    # com in body frame
    lines.append(carr("body_iquat", m.body_iquat, 4))  # inertial frame in body (wxyz)
    lines.append(carr("body_mass", m.body_mass, 1))
    lines.append(carr("body_inertia", m.body_inertia, 3))  # diag inertia in iquat frame
    lines.append(iarr("body_jntnum", m.body_jntnum))
    lines.append(iarr("body_jntadr", m.body_jntadr))
    lines.append(iarr("body_dofadr", m.body_dofadr))
    lines.append(iarr("body_dofnum", m.body_dofnum))

    # --- joints ---
    lines.append(iarr("jnt_type", m.jnt_type))   # mjtJoint: 0=free,1=ball,2=slide,3=hinge
    lines.append(iarr("jnt_bodyid", m.jnt_bodyid))
    lines.append(iarr("jnt_qposadr", m.jnt_qposadr))
    lines.append(iarr("jnt_dofadr", m.jnt_dofadr))
    lines.append(carr("jnt_axis", m.jnt_axis, 3))  # in body local frame
    lines.append(carr("jnt_pos", m.jnt_pos, 3))    # anchor in body local frame

    # --- dofs ---
    lines.append(carr("dof_armature", m.dof_armature, 1))

    # --- reference / initial state ---
    lines.append(carr("qpos0", m.qpos0, 1))  # joint reference pose
    # stable standing keyframe (bent knees) -- the equilibrium pose the RL env resets to.
    # qpos0 has straight legs which sits the feet right at the ground and is contact-unstable.
    if m.nkey > 0:
        lines.append(carr("g1_qpos_stand", m.key_qpos[0], 1))

    # --- collision geometry (foot spheres vs ground plane) for the contact solver ---
    # Use scene.xml so the ground plane + full contact params are present (g1.xml alone
    # has no floor). Foot collision spheres = the only contacts that matter for locomotion.
    try:
        scene = os.path.join(HERE, "models", "scene.xml")
        ms = mujoco.MjModel.from_xml_path(scene)
        foot_body, foot_lpos, foot_r = [], [], []
        for g in range(ms.ngeom):
            if ms.geom_type[g] == int(mujoco.mjtGeom.mjGEOM_SPHERE) and \
               (ms.geom_contype[g] or ms.geom_conaffinity[g]):
                foot_body.append(int(ms.geom_bodyid[g]))
                foot_lpos.append(ms.geom_pos[g])
                foot_r.append(float(ms.geom_size[g, 0]))
        nfs = len(foot_body)
        # contact params taken from the foot geoms (priority 1 -> these win on mixing).
        # condim/friction/solref/solimp are uniform across the foot spheres here.
        gi = next(g for g in range(ms.ngeom)
                  if ms.geom_type[g] == int(mujoco.mjtGeom.mjGEOM_SPHERE)
                  and (ms.geom_contype[g] or ms.geom_conaffinity[g]))
        lines.append(f"\n// --- contact / collision (from models/scene.xml) ---")
        lines.append(f"#define G1_NFOOT_SPHERE {nfs}")
        lines.append(f"#define G1_FOOT_RADIUS {fmtf(foot_r[0])}")
        lines.append(f"#define G1_FOOT_MU {fmtf(ms.geom_friction[gi, 0])}")
        lines.append(f"#define G1_FOOT_CONDIM {int(ms.geom_condim[gi])}")
        lines.append(iarr("g1_foot_body", foot_body))
        lines.append(carr("g1_foot_lpos", np.array(foot_lpos), 3))
        sr = ms.geom_solref[gi]; si = ms.geom_solimp[gi]
        lines.append(f"__device__ __constant__ float G1_FOOT_SOLREF[2] = {{ {fmtf(sr[0])}, {fmtf(sr[1])} }};")
        lines.append(f"__device__ __constant__ float G1_FOOT_SOLIMP[5] = "
                     f"{{ {', '.join(fmtf(v) for v in si)} }};")
        lines.append(f"#define G1_FOOT_IMPRATIO {fmtf(ms.opt.impratio)}")
        lines.append(f"// impratio = {ms.opt.impratio:.6g}, cone = "
                     f"{mujoco.mjtCone(ms.opt.cone).name}, solver = "
                     f"{mujoco.mjtSolver(ms.opt.solver).name}")
        # per-sphere body_invweight0 (translational): needed to reconstruct efc_R on-device.
        # diagApprox(pyramidal) = (invw0_body + invw0_floor)*(1+mu^2)*(2*mu^2/impratio),
        # R = diagApprox*(1-imp)/imp. Floor (body 0) invweight is 0. See contact_np2.py.
        foot_iw = [float(ms.body_invweight0[b, 0]) for b in foot_body]
        lines.append("// body_invweight0[b,0] (translational) per foot sphere, MuJoCo-stored.")
        lines.append(carr("g1_foot_body_invweight0", np.array(foot_iw), len(foot_iw)))
        print(f"  contact geoms: {nfs} foot spheres, r={foot_r[0]}, mu={ms.geom_friction[gi,0]}, "
              f"condim={ms.geom_condim[gi]}, impratio={ms.opt.impratio}")
    except Exception as e:  # noqa: BLE001
        lines.append(f"\n// WARNING: contact geometry export failed: {e}")
        print(f"  contact geometry export FAILED: {e}")

    # --- position (PD) actuators: policy outputs joint targets, tau = kp*(target-q) - kd*qd.
    # Additive: these constants are only used by the RL env kernel (src/g1_env.cu); the
    # validated ABA/contact path does not read them. trnid -> joint -> dof gives the
    # actuated-dof index for each of the nu actuators (G1: 29 hinges, dofs 6..34).
    try:
        nu = m.nu
        kp = m.actuator_gainprm[:, 0].copy()
        kd = -m.actuator_biasprm[:, 2].copy()  # biasprm[:,2] = -kv
        act_dof = np.array([int(m.jnt_dofadr[m.actuator_trnid[a, 0]]) for a in range(nu)])
        clo = m.actuator_ctrlrange[:, 0].copy()
        chi = m.actuator_ctrlrange[:, 1].copy()
        lines.append("\n// --- position (PD) actuators (from models/g1.xml) ---")
        lines.append(f"#define G1_NU {nu}")
        lines.append(iarr("g1_act_dof", act_dof))   # generalized-velocity dof per actuator
        lines.append(carr("g1_act_kp", kp, nu))
        lines.append(carr("g1_act_kd", kd, nu))
        lines.append(carr("g1_act_ctrl_lo", clo, nu))
        lines.append(carr("g1_act_ctrl_hi", chi, nu))
        # qpos address per actuated joint (for target-vs-current position error)
        act_qadr = np.array([int(m.jnt_qposadr[m.actuator_trnid[a, 0]]) for a in range(nu)])
        lines.append(iarr("g1_act_qadr", act_qadr))
        # actuator force (torque) limits: jnt_actfrcrange. MuJoCo clamps qfrc_actuator to this
        # per-joint range AFTER computing the PD torque -- the RL env must replicate it to match
        # implicitfast and for physical realism (the kd damping stays implicit, applied to the
        # un-clamped velocity-feedback derivative -> matches MuJoCo to fp precision).
        frc_lo = np.array([float(m.jnt_actfrcrange[m.actuator_trnid[a, 0], 0]) for a in range(nu)])
        frc_hi = np.array([float(m.jnt_actfrcrange[m.actuator_trnid[a, 0], 1]) for a in range(nu)])
        lines.append(carr("g1_act_frc_lo", frc_lo, nu))
        lines.append(carr("g1_act_frc_hi", frc_hi, nu))
        print(f"  actuators: nu={nu} position(PD) kp={kp[0]:.0f} kd[{kd.min():.2f},{kd.max():.2f}] "
              f"frc_hi[{frc_hi.min():.0f},{frc_hi.max():.0f}]")
    except Exception as e:  # noqa: BLE001
        lines.append(f"\n// WARNING: actuator export failed: {e}")
        print(f"  actuator export FAILED: {e}")

    header = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(header)

    # sanity print
    jtn = {0: "free", 1: "ball", 2: "slide", 3: "hinge"}
    print(f"wrote {OUT}")
    print(f"  nbody={nb} nq={nq} nv={nv} njnt={njnt}")
    print(f"  joint types: {[jtn[int(t)] for t in m.jnt_type][:5]} ...")
    print(f"  total mass = {m.body_mass.sum():.3f} kg")
    print(f"  header bytes = {len(header)}")


if __name__ == "__main__":
    main()
