#!/usr/bin/env python3
"""Codegen the specialized straight-line ABA kernel for the FIXED G1 tree.

Mirrors src/aba_fp16.cuh EXACTLY (fp16 storage of the IA + vel/cb/pA/a6 working
set, fp32 compute) but replaces every RUNTIME tree index (par=body_parentid[b],
body_dofadr[b], ...) with a COMPILE-TIME LITERAL, and replaces every per-body
spatial array element with a NAMED SCALAR LOCAL. Hypothesis: no runtime indexing
-> compiler register-allocates/schedules the hot subset, dropping the runtime-
indexed local-memory ops (518 in SASS) that make the array kernel DRAM-bound.

Per-body quantities stored as named scalars (fp16 half) to match aba_fp16:
  IA_b_0..20  (21 packed symmetric spatial/articulated inertia)
  vel_b_0..5, cb_b_0..5, pA_b_0..5, a6_b_0..5

Emits src/aba_codegen.cuh with __device__ void aba_qacc_gen(...).
Reads the fixed tree from src/g1_model.h (parsed) so it stays in sync.
"""
import os, re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = os.path.join(HERE, "src", "g1_model.h")
OUT = os.path.join(HERE, "src", "aba_codegen.cuh")


def parse_int_array(txt, name):
    m = re.search(r"\b%s\s*\[\s*\d*\s*\]\s*=\s*\{([^}]*)\}" % name, txt)
    return [int(x) for x in m.group(1).replace("\n", " ").split(",") if x.strip()]


def main():
    txt = open(MODEL).read()
    NB = int(re.search(r"#define G1_NBODY (\d+)", txt).group(1))
    NV = int(re.search(r"#define G1_NV (\d+)", txt).group(1))
    parent = parse_int_array(txt, "body_parentid")
    dofadr = parse_int_array(txt, "body_dofadr")
    dofnum = parse_int_array(txt, "body_dofnum")
    assert len(parent) == NB

    # symidx mirrors the C helper: packed upper-tri of symmetric 6x6 (21 unique)
    def symidx(i, j):
        if i > j:
            i, j = j, i
        return i * 6 - (i * (i - 1)) // 2 + (j - i)

    L = []
    w = L.append
    w("// GENERATED by scripts/gen_aba_kernel.py -- do not edit by hand.")
    w("// Straight-line specialized ABA for the FIXED G1 tree. Every parent index is a")
    w("// compile-time literal; every per-body spatial quantity is a named scalar local.")
    w("// Mirrors the math + fp16 storage idea of src/aba_fp16.cuh. armature D fix kept.")
    w("#pragma once")
    w('#include "aba.cuh"')
    w("#include <cuda_fp16.h>")
    w("")
    w("__device__ void aba_qacc_gen(const float* qpos, const float* qvel,")
    w("                             const float* xpos, const float* xquat, const float* xipos,")
    w("                             float* S, float* qacc) {")
    w("    V3 p={xpos[3],xpos[4],xpos[5]};")
    w("    Q4 q1={xquat[4],xquat[5],xquat[6],xquat[7]};")
    w("    M3 R1=quat2mat(q1);")
    w("")
    # ---- motion axes S (same as aba_fp16; S stays an array, it is read-only after build) ----
    w("    for (int i=0;i<%d*6;++i) S[i]=0.f;" % NV)
    w("    for (int j=0;j<G1_NJNT;++j){")
    w("        int t=jnt_type[j], b=jnt_bodyid[j], d=jnt_dofadr[j];")
    w("        if (t==0){")
    w("            S[(d+0)*6+3]=1; S[(d+1)*6+4]=1; S[(d+2)*6+5]=1;")
    w("            for (int k=0;k<3;++k){ V3 ax=col(R1,k); S[(d+3+k)*6+0]=ax.x; S[(d+3+k)*6+1]=ax.y; S[(d+3+k)*6+2]=ax.z; }")
    w("        } else if (t==3){")
    w("            Q4 qb={xquat[4*b],xquat[4*b+1],xquat[4*b+2],xquat[4*b+3]};")
    w("            V3 aw=qrot(qb,(V3){jnt_axis[3*j],jnt_axis[3*j+1],jnt_axis[3*j+2]});")
    w("            V3 anchor=vadd((V3){xpos[3*b],xpos[3*b+1],xpos[3*b+2]}, qrot(qb,(V3){jnt_pos[3*j],jnt_pos[3*j+1],jnt_pos[3*j+2]}));")
    w("            V3 r=vsub(anchor,p), rxa=cross(r,aw);")
    w("            S[d*6+0]=aw.x; S[d*6+1]=aw.y; S[d*6+2]=aw.z; S[d*6+3]=rxa.x; S[d*6+4]=rxa.y; S[d*6+5]=rxa.z;")
    w("        }")
    w("    }")
    w("")

    # declare named scalar locals (fp16) for the per-body working set
    for b in range(1, NB):
        w("    __half " + ", ".join("IA_%d_%d" % (b, s) for s in range(21)) + ";")
    for b in range(1, NB):
        w("    __half " + ", ".join("vel_%d_%d" % (b, k) for k in range(6)) + ";")
        w("    __half " + ", ".join("cb_%d_%d" % (b, k) for k in range(6)) + ";")
        w("    __half " + ", ".join("pA_%d_%d" % (b, k) for k in range(6)) + ";")
    for b in range(1, NB):
        w("    __half " + ", ".join("a6_%d_%d" % (b, k) for k in range(6)) + ";")
    w("")

    # ---- per-body spatial inertia -> IA scalars (loop body inlined per b with literal b) ----
    w("    {")
    for b in range(1, NB):
        w("    { const int b=%d;" % b)
        w("      Q4 qb={xquat[4*b],xquat[4*b+1],xquat[4*b+2],xquat[4*b+3]};")
        w("      Q4 qi={body_iquat[4*b],body_iquat[4*b+1],body_iquat[4*b+2],body_iquat[4*b+3]};")
        w("      M3 Ri=quat2mat(qmul(qb,qi));")
        w("      V3 di={body_inertia[3*b],body_inertia[3*b+1],body_inertia[3*b+2]};")
        w("      M3 Iw=world_inertia(Ri,di);")
        w("      float m=body_mass[b];")
        w("      V3 c={xipos[3*b]-p.x,xipos[3*b+1]-p.y,xipos[3*b+2]-p.z};")
        w("      float cc=dot3(c,c);")
        w("      float A[9]; for(int i=0;i<9;++i)A[i]=Iw.m[i];")
        w("      A[0]+=m*(cc-c.x*c.x);A[1]+=m*(-c.x*c.y);A[2]+=m*(-c.x*c.z);")
        w("      A[3]+=m*(-c.y*c.x);A[4]+=m*(cc-c.y*c.y);A[5]+=m*(-c.y*c.z);")
        w("      A[6]+=m*(-c.z*c.x);A[7]+=m*(-c.z*c.y);A[8]+=m*(cc-c.z*c.z);")
        w("      float Bx[9]={0,-c.z,c.y, c.z,0,-c.x, -c.y,c.x,0};")
        w("      float M6[36];")
        w("      for(int i=0;i<3;++i)for(int j=0;j<3;++j){")
        w("        M6[6*i+j]=A[3*i+j]; M6[6*i+(j+3)]=m*Bx[3*i+j];")
        w("        M6[6*(i+3)+j]=-m*Bx[3*i+j]; M6[6*(i+3)+(j+3)]=(i==j)?m:0.f; }")
        for i in range(6):
            for j in range(i, 6):
                w("      IA_%d_%d=__float2half(M6[%d]);" % (b, symidx(i, j), i * 6 + j))
        w("    }")
    w("    }")
    w("")

    # ---- pass 1: velocities + bias accel ----
    # body 1 has parent 0 (world): w = 0
    w("    // ---- pass 1: velocities v[b], bias accel c[b] ----")
    for b in range(1, NB):
        par = parent[b]
        da = dofadr[b]
        dn = dofnum[b]
        w("    {")
        if par == 0:
            w("      float w[6]={0,0,0,0,0,0};")
        else:
            w("      float w[6]={%s};" % ",".join("__half2float(vel_%d_%d)" % (par, k) for k in range(6)))
        w("      float c6[6]={0,0,0,0,0,0};")
        # add_sdot lambda inlined as macro-style block using S array (S read-only, literal dof a)
        w("      #define ADD_SDOT(a, wpart) do { \\")
        w("        V3 pw={wpart[0],wpart[1],wpart[2]}, pv={wpart[3],wpart[4],wpart[5]}; \\")
        w("        V3 sw={S[(a)*6+0],S[(a)*6+1],S[(a)*6+2]}, sv={S[(a)*6+3],S[(a)*6+4],S[(a)*6+5]}; \\")
        w("        V3 ow,ov; crossm(pw,pv,sw,sv,ow,ov); float qd=qvel[a]; \\")
        w("        c6[0]+=ow.x*qd; c6[1]+=ow.y*qd; c6[2]+=ow.z*qd; \\")
        w("        c6[3]+=ov.x*qd; c6[4]+=ov.y*qd; c6[5]+=ov.z*qd; } while(0)")
        if dn == 6:
            w("      for(int a=%d;a<%d;++a){ ADD_SDOT(a,w); float qd=qvel[a]; for(int k=0;k<6;++k) w[k]+=S[a*6+k]*qd; }" % (da, da + 3))
            w("      float wr[6]; for(int k=0;k<6;++k) wr[k]=w[k];")
            w("      for(int a=%d;a<%d;++a) ADD_SDOT(a,wr);" % (da + 3, da + 6))
            w("      for(int a=%d;a<%d;++a){ float qd=qvel[a]; for(int k=0;k<6;++k) w[k]+=S[a*6+k]*qd; }" % (da + 3, da + 6))
        else:
            w("      for(int a=%d;a<%d;++a){ ADD_SDOT(a,w); float qd=qvel[a]; for(int k=0;k<6;++k) w[k]+=S[a*6+k]*qd; }" % (da, da + dn))
        w("      #undef ADD_SDOT")
        for k in range(6):
            w("      vel_%d_%d=__float2half(w[%d]); cb_%d_%d=__float2half(c6[%d]);" % (b, k, k, b, k, k))
        w("    }")
    w("")

    # pA init = v x* (I_body v)
    w("    // ---- pA init = v x* (I_body v) ----")
    for b in range(1, NB):
        w("    {")
        w("      float v6[6]={%s};" % ",".join("__half2float(vel_%d_%d)" % (b, k) for k in range(6)))
        w("      float Pk[21]={%s};" % ",".join("__half2float(IA_%d_%d)" % (b, s) for s in range(21)))
        w("      float Iv[6]; symmv6(Pk,v6,Iv);")
        w("      float pa[6]; crossf6(v6,Iv,pa);")
        for k in range(6):
            w("      pA_%d_%d=__float2half(pa[%d]);" % (b, k, k))
        w("    }")
    w("")

    # ---- pass 2: leaf->root (b from NB-1 down to 2), accumulate into parent ----
    w("    // ---- pass 2: leaf->root articulated inertia/bias propagation ----")
    for b in range(NB - 1, 1, -1):
        par = parent[b]
        d = dofadr[b]
        w("    {")
        w("      float Pk[21]={%s};" % ",".join("__half2float(IA_%d_%d)" % (b, s) for s in range(21)))
        w("      float U[6]; symmv6(Pk,&S[%d*6],U);" % d)
        w("      float D=dot6(&S[%d*6],U) + dof_armature[%d];" % (d, d))
        w("      float pAb[6]={%s};" % ",".join("__half2float(pA_%d_%d)" % (b, k) for k in range(6)))
        w("      float u=-dot6(&S[%d*6],pAb);" % d)
        w("      float invD=1.f/D;")
        w("      float Ia[21]; for(int i=0;i<6;++i)for(int j=i;j<6;++j){ int s=symidx(i,j); Ia[s]=Pk[s]-U[i]*U[j]*invD; }")
        w("      float cbb[6]={%s};" % ",".join("__half2float(cb_%d_%d)" % (b, k) for k in range(6)))
        w("      float Iac[6]; symmv6(Ia,cbb,Iac);")
        w("      float pa[6]; for(int k=0;k<6;++k) pa[k]=pAb[k]+Iac[k]+U[k]*(u*invD);")
        # accumulate Ia into parent IA scalars
        for s in range(21):
            w("      IA_%d_%d=__float2half(__half2float(IA_%d_%d)+Ia[%d]);" % (par, s, par, s, s))
        # accumulate pa into parent pA scalars
        for k in range(6):
            w("      pA_%d_%d=__float2half(__half2float(pA_%d_%d)+pa[%d]);" % (par, k, par, k, k))
        w("    }")
    w("")

    # ---- pass 3: root->leaf accelerations ----
    w("    // ---- pass 3: root->leaf accelerations ----")
    w("    float a0[6]={0,0,0,-G1_GRAVITY[0],-G1_GRAVITY[1],-G1_GRAVITY[2]};")
    # base body 1 (free joint): 6x6 solve. parent is 0 -> ap = a0 + cb
    b = 1
    d = dofadr[b]
    w("    {")
    w("      const int d=%d;" % d)
    w("      float cbb[6]={%s};" % ",".join("__half2float(cb_1_%d)" % k for k in range(6)))
    w("      float ap[6]; for(int k=0;k<6;++k) ap[k]=a0[k]+cbb[k];")
    w("      float pAb[6]={%s};" % ",".join("__half2float(pA_1_%d)" % k for k in range(6)))
    w("      float Pk[21]={%s};" % ",".join("__half2float(IA_1_%d)" % s for s in range(21)))
    w("      float U[36], Dm[36], rhs[6];")
    w("      for(int l=0;l<6;++l){ float Ul[6]; symmv6(Pk,&S[(d+l)*6],Ul); for(int i=0;i<6;++i) U[i*6+l]=Ul[i]; }")
    w("      for(int k=0;k<6;++k)for(int l=0;l<6;++l){ float s=0; for(int i=0;i<6;++i) s+=S[(d+k)*6+i]*U[i*6+l]; Dm[k*6+l]=s + (k==l?dof_armature[d+k]:0.f); }")
    w("      for(int k=0;k<6;++k){ float uk=-dot6(&S[(d+k)*6],pAb); float UTa=0; for(int i=0;i<6;++i) UTa+=U[i*6+k]*ap[i]; rhs[k]=uk-UTa; }")
    w("      float qdd[6]; chol6_solve(Dm,rhs,qdd);")
    w("      for(int k=0;k<6;++k) qacc[d+k]=qdd[k];")
    w("      float aw[6]; for(int i=0;i<6;++i){ float Sq=0; for(int k=0;k<6;++k) Sq+=S[(d+k)*6+i]*qdd[k]; aw[i]=ap[i]+Sq; }")
    for k in range(6):
        w("      a6_1_%d=__float2half(aw[%d]);" % (k, k))
    w("    }")
    for b in range(2, NB):
        par = parent[b]
        d = dofadr[b]
        w("    {")
        w("      const int d=%d;" % d)
        w("      float ap6[6]={%s};" % ",".join("__half2float(a6_%d_%d)" % (par, k) for k in range(6)))
        w("      float cbb[6]={%s};" % ",".join("__half2float(cb_%d_%d)" % (b, k) for k in range(6)))
        w("      float ap[6]; for(int k=0;k<6;++k) ap[k]=ap6[k]+cbb[k];")
        w("      float Pk[21]={%s};" % ",".join("__half2float(IA_%d_%d)" % (b, s) for s in range(21)))
        w("      float U[6]; symmv6(Pk,&S[d*6],U);")
        w("      float D=dot6(&S[d*6],U) + dof_armature[d];")
        w("      float pAb[6]={%s};" % ",".join("__half2float(pA_%d_%d)" % (b, k) for k in range(6)))
        w("      float u=-dot6(&S[d*6],pAb);")
        w("      float qdd=(u - dot6(U,ap))/D;")
        w("      qacc[d]=qdd;")
        w("      float aw[6]; for(int i=0;i<6;++i) aw[i]=ap[i]+S[d*6+i]*qdd;")
        for k in range(6):
            w("      a6_%d_%d=__float2half(aw[%d]);" % (b, k, k))
        w("    }")
    w("}")
    w("")

    open(OUT, "w").write("\n".join(L))
    print("wrote %s (%d lines, NB=%d NV=%d)" % (OUT, len(L), NB, NV))


if __name__ == "__main__":
    main()
